<a href="https://colab.research.google.com/github/Mubby03/Machine-Deep-Learning-Pancakes/blob/main/LengthOfStayExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive to access files stored in your Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# Install necessary libraries
# numpy<2 is specified to avoid potential conflicts with other libraries that might require an older version
!pip install -q "numpy<2" --force-reinstall
# Install scikit-learn-extra for KMedoids clustering
!pip3 install scikit-learn-extra

# Import essential libraries for data manipulation, scaling, and clustering
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn_extra.cluster import KMedoids
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Requirement already satisfied: scikit-learn-extra in /usr/local/lib/python3.12/dist-packages (0.3.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra) (1.26.4)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra) (1.16.3)
Requirement already satisfied: scikit-learn>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.23.0->scikit-learn-extra) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.23.0->scikit-learn-extra) (3.6.0)

In [3]:
# Load the dataset from Google Drive into a pandas DataFrame
df = pd.read_csv("/content/drive/MyDrive/Lengthofstay.csv")
# Display the first few rows of the DataFrame to get an overview of the data
df.head()

,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,...,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,lengthofstay
0,0,0,0,0,0,0,0,0,0,0,...,14.20,140.361132,192.476918,12.0,1.390722,30.432418,96,6.5,4,3
1,0,0,0,0,0,0,0,0,0,0,...,4.10,136.731692,94.078507,8.0,0.943164,28.460516,61,6.5,1,7
2,0,0,0,0,0,0,0,0,0,0,...,8.90,133.058514,130.530524,12.0,1.065750,28.843812,64,6.5,2,3
3,0,0,0,0,0,0,0,0,0,0,...,9.40,138.994023,163.377028,12.0,0.906862,27.959007,76,6.5,1,1
4,0,0,0,0,1,0,1,0,0,0,...,9.05,138.634836,94.886654,11.5,1.242854,30.258927,67,5.6,2,4

In [4]:
# Display the names of all columns in the DataFrame
df.columns

Index(['gender', 'dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'respiration', 'secondarydiagnosisnonicd9',
       'lengthofstay'],
      dtype='object')

In [5]:
# Generate descriptive statistics of the DataFrame
# .T (transpose) is used to make the output more readable, showing statistics per column
df.describe().T

,count,mean,std,min,25%,50%,75%,max
gender,100000.0,0.423570,0.494126,0.000000,0.000000,0.000000,1.000000,1.000000
dialysisrenalendstage,100000.0,0.036420,0.187334,0.000000,0.000000,0.000000,0.000000,1.000000
asthma,100000.0,0.035270,0.184462,0.000000,0.000000,0.000000,0.000000,1.000000
irondef,100000.0,0.094940,0.293134,0.000000,0.000000,0.000000,0.000000,1.000000
pneum,100000.0,0.039450,0.194664,0.000000,0.000000,0.000000,0.000000,1.000000
substancedependence,100000.0,0.063060,0.243072,0.000000,0.000000,0.000000,0.000000,1.000000
psychologicaldisordermajor,100000.0,0.239040,0.426499,0.000000,0.000000,0.000000,0.000000,1.000000
depress,100000.0,0.051660,0.221341,0.000000,0.000000,0.000000,0.000000,1.000000
psychother,100000.0,0.049390,0.216682,0.000000,0.000000,0.000000,0.000000,1.000000
fibrosisandother,100000.0,0.004790,0.069044,0.000000,0.000000,0.000000,0.000000,1.000000
malnutrition,100000.0,0.049480,0.216869,0.000000,0.000000,0.000000,0.000000,1.000000
hemo,100000.0,0.080000,0.271295,0.000000,0.000000,0.000000,0.000000,1.000000
hematocrit,100000.0,11.975939,2.031792,4.400000,10.900000,11.900000,12.900000,24.100000
neutrophils,100000.0,10.177455,5.353131,0.100000,7.700000,9.400000,11.500000,245.900000
sodium,100000.0,137.891397,2.999669,124.912632,135.871062,137.887151,139.912885,151.387283
glucose,100000.0,141.963384,29.992996,-1.005927,121.682383,142.088545,162.180996,271.444277
bloodureanitro,100000.0,14.097185,12.952454,1.000000,11.000000,12.000000,14.000000,682.500000
creatinine,100000.0,1.099350,0.200262,0.219770,0.964720,1.098764,1.234867,2.035202
bmi,100000.0,29.805759,2.003769,21.992683,28.454235,29.807516,31.156885,38.935293
pulse,100000.0,73.444720,11.644555,21.000000,66.000000,73.000000,81.000000,130.000000
respiration,100000.0,6.493768,0.568473,0.200000,6.500000,6.500000,6.500000,10.000000
secondarydiagnosisnonicd9,100000.0,2.123310,2.050641,0.000000,1.000000,1.000000,3.000000,10.000000
lengthofstay,100000.0,4.001030,2.360310,1.000000,2.000000,4.000000,6.000000,17.000000

In [6]:
# Display the number of rows and columns in the DataFrame
df.shape

(100000, 23)

In [7]:
# Check for missing values in each column and sum them up
df.isnull().sum()

gender                        0
dialysisrenalendstage         0
asthma                        0
irondef                       0
pneum                         0
substancedependence           0
psychologicaldisordermajor    0
depress                       0
psychother                    0
fibrosisandother              0
malnutrition                  0
hemo                          0
hematocrit                    0
neutrophils                   0
sodium                        0
glucose                       0
bloodureanitro                0
creatinine                    0
bmi                           0
pulse                         0
respiration                   0
secondarydiagnosisnonicd9     0
lengthofstay                  0
dtype: int64

In [8]:
# Initialize the StandardScaler to normalize the data
scaler = StandardScaler()
# Fit the scaler to the DataFrame and transform the data
Clus_dataSet = scaler.fit_transform(df)
# Convert the scaled data back into a pandas DataFrame for easier manipulation
scaled_features_clus = pd.DataFrame(Clus_dataSet )

##Kmeans Clustering

> Add blockquote

In [9]:
# Define the number of clusters for KMeans
kclusters = 3
# Initialize KMeans model with the specified number of clusters and a random state for reproducibility
kmeans = KMeans(n_clusters=kclusters, random_state=42)
# Fit the KMeans model to the scaled dataset
kmeans.fit(Clus_dataSet)

Exception ignored on calling ctypes callback function: <function ThreadpoolController._find_libraries_with_dl_iterate_phdr.<locals>.match_library_callback at 0x7f1c1eea54e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/threadpoolctl.py", line 1005, in match_library_callback
    self._make_controller_from_path(filepath)
  File "/usr/local/lib/python3.12/dist-packages/threadpoolctl.py", line 1187, in _make_controller_from_path
    lib_controller = controller_class(
                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/threadpoolctl.py", line 114, in __init__
    self.dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen() error

KMeans(n_clusters=3, random_state=42)

In [10]:
# Display the first 100 cluster labels assigned by KMeans
kmeans.labels_[0:100]

array([2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 0, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 0, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 0, 2, 2, 1, 1, 2, 2, 2, 1,
       2, 2, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0], dtype=int32)

In [11]:
# Count the number of data points assigned to each cluster
pd.Series(kmeans.labels_).value_counts()

2    70013
1    21273
0     8714
Name: count, dtype: int64

In [12]:
# Insert the KMeans cluster labels as a new column at the beginning of the original DataFrame
df.insert(0, 'kmeans Cluster Labels', kmeans.labels_)
# Display the first 100 rows of the modified DataFrame to see the new cluster labels
df.head(100)

,kmeans Cluster Labels,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,lengthofstay
0,2,0,0,0,0,0,0,0,0,0,...,14.20,140.361132,192.476918,12.0,1.390722,30.432418,96,6.5,4,3
1,2,0,0,0,0,0,0,0,0,0,...,4.10,136.731692,94.078507,8.0,0.943164,28.460516,61,6.5,1,7
2,2,0,0,0,0,0,0,0,0,0,...,8.90,133.058514,130.530524,12.0,1.065750,28.843812,64,6.5,2,3
3,2,0,0,0,0,0,0,0,0,0,...,9.40,138.994023,163.377028,12.0,0.906862,27.959007,76,6.5,1,1
4,1,0,0,0,0,1,0,1,0,0,...,9.05,138.634836,94.886654,11.5,1.242854,30.258927,67,5.6,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,1,0,0,0,0,0,0,0,0,...,33.10,137.238594,110.691564,12.0,1.010614,27.794394,53,6.5,2,5
96,2,1,0,0,0,0,0,0,0,0,...,11.50,139.689694,181.736708,9.0,1.210496,32.171026,74,6.6,1,2
97,0,0,1,0,1,1,0,0,0,0,...,6.00,138.868964,139.575249,53.5,1.043159,30.217921,70,7.0,1,5
98,2,0,0,0,0,0,0,0,0,0,...,7.20,138.323722,175.101714,12.0,1.035046,31.547415,48,6.5,0,1
99,0,1,0,0,1,0,0,0,0,1,...,10.40,137.225532,154.362229,20.0,1.087789,32.532790,70,5.3,3,4

In [13]:
# Calculate and print the Silhouette Score for the KMeans clustering
# The Silhouette Score measures how similar an object is to its own cluster compared to other clusters
print('Silhouette Score:', '%.2f'%silhouette_score(Clus_dataSet, kmeans.labels_))

Silhouette Score: 0.14

In [14]:
# Add the KMeans cluster labels to the DataFrame containing scaled features
scaled_features_clus['cluster'] = kmeans.labels_

In [15]:
# Create separate DataFrames for each cluster based on KMeans labels
cluster1=scaled_features_clus.query("cluster == 0")
cluster2=scaled_features_clus.query("cluster == 1")
cluster3=scaled_features_clus.query("cluster == 2")

In [16]:
# Display the first few rows of cluster 1
cluster1.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,cluster
22,1.166570,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,-0.560473,-0.233397,-0.227939,-0.069376,...,-0.173435,0.170995,1.073378,-0.171498,-0.730660,-0.295824,-0.516769,-0.547788,0.846914,0
23,1.166570,-0.194413,-0.191205,3.087551,-0.202658,-0.259431,-0.560473,-0.233397,-0.227939,-0.069376,...,0.455081,-0.656008,1.613819,-0.141096,-0.050530,2.366378,-1.044502,-0.547788,-0.000436,0
24,-0.857214,5.143680,-0.191205,-0.323881,4.934424,3.854596,-0.560473,-0.233397,-0.227939,-0.069376,...,-0.696554,0.280027,6.941022,0.743626,-1.940314,-0.982844,-1.572234,-0.547788,0.846914,0
25,1.166570,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,1.784209,-0.233397,4.387142,-0.069376,...,-0.896967,0.231324,1.613819,-0.659751,0.723550,0.648828,-1.044502,-0.547788,-0.000436,0
42,-0.857214,5.143680,-0.191205,3.087551,-0.202658,-0.259431,-0.560473,-0.233397,-0.227939,-0.069376,...,0.194492,-1.623094,0.532938,0.678180,-0.573320,-0.467579,-1.924055,-0.547788,0.423239,0

In [17]:
# Display the shape (number of rows and columns) of cluster 1
cluster1.shape

(8714, 24)

In [18]:
# Generate descriptive statistics for cluster 1
cluster1.describe()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,cluster
count,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,...,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.000000,8714.0
mean,0.425243,1.678269,-0.002080,1.130499,0.643304,0.383121,0.415177,-0.017195,2.264438,0.141711,...,-0.000466,0.000689,1.428307,-0.015999,0.003918,0.017372,-0.229597,0.021964,0.837239,0.0
std,0.975104,2.547618,0.994802,1.687194,1.905398,1.493605,1.155789,0.964443,2.300258,1.735821,...,1.014218,1.022823,2.792543,1.015946,1.015322,1.005475,1.499156,1.015937,0.956537,0.0
min,-0.857214,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,-0.560473,-0.233397,-0.227939,-0.069376,...,-3.547894,-3.638497,-0.856767,-4.205507,-3.730417,-4.332065,-10.895503,-1.035443,-1.271462,0.0
25%,-0.857214,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,-0.560473,-0.233397,-0.227939,-0.069376,...,-0.692939,-0.687774,0.301320,-0.711126,-0.677406,-0.639334,-0.868591,-0.547788,-0.000436,0.0
50%,1.166570,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,-0.560473,-0.233397,4.387142,-0.069376,...,-0.014773,0.005730,0.841761,-0.022240,-0.005772,0.047686,0.010963,-0.547788,0.846914,0.0
75%,1.166570,5.143680,-0.191205,3.087551,-0.202658,-0.259431,1.784209,-0.233397,4.387142,-0.069376,...,0.686472,0.688098,1.691025,0.671402,0.683216,0.734706,0.362784,0.427522,1.270589,0.0
max,1.166570,5.143680,5.229982,3.087551,4.934424,3.854596,1.784209,4.284546,4.387142,14.414169,...,4.309361,4.221266,51.604595,3.686496,3.805831,3.998050,6.167839,3.841107,5.507342,0.0

In [19]:
# Display the first few rows of cluster 2
cluster2.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,cluster
4,-0.857214,-0.194413,-0.191205,-0.323881,4.934424,-0.259431,1.784209,-0.233397,-0.227939,-0.069376,...,0.247842,-1.569599,-0.200518,0.716587,0.226159,-0.553456,-1.572234,-0.060133,-0.000436,1
7,-0.857214,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,1.784209,-0.233397,-0.227939,-0.069376,...,-0.607306,0.343498,-0.239121,-1.654063,1.593710,-0.896966,-0.868591,0.427522,-0.424112,1
26,-0.857214,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,1.784209,-0.233397,-0.227939,-0.069376,...,-0.011099,0.575531,-0.547944,-0.928861,2.832870,1.249971,2.121892,-1.035443,1.270589,1
31,-0.857214,-0.194413,-0.191205,-0.323881,-0.202658,-0.259431,1.784209,-0.233397,-0.227939,-0.069376,...,-0.624498,0.106183,-0.316327,-0.003349,0.445696,-0.124069,-1.220412,-0.547788,-0.424112,1
37,1.166570,-0.194413,-0.191205,-0.323881,4.934424,-0.259431,1.784209,-0.233397,-0.227939,-0.069376,...,1.013046,-0.850439,-0.239121,1.118042,-2.973555,0.391196,2.297803,0.915177,2.541615,1

In [20]:
# Display the coordinates of the cluster centers (centroids) identified by KMeans
kmeans.cluster_centers_

array([[ 4.25034139e-01,  1.67762410e+00, -2.14471158e-03,
         1.12999836e+00,  6.43012965e-01,  3.82899463e-01,
         4.15648552e-01, -1.72695722e-02,  2.26622717e+00,
         1.39976427e-01,  2.04856340e+00,  8.56557084e-01,
        -5.78285388e-01, -3.12773529e-01, -4.79531504e-05,
         6.72592843e-04,  1.42787514e+00, -1.62251995e-02,
         3.80966102e-03,  1.72146635e-02, -2.28969508e-01,
         2.18237323e-02,  8.36318546e-01],
       [ 1.91066519e-01, -1.31178288e-01,  6.26142344e-02,
         6.62852419e-02,  4.89680949e-02,  8.77080094e-02,
         1.67288775e+00,  7.75191978e-01, -2.04508726e-01,
        -4.69622126e-03, -1.56410214e-01, -1.62599929e-02,
         1.93172457e-01, -2.20143935e-01, -6.27447142e-03,
        -3.09331939e-03, -9.25900649e-02,  3.05849997e-03,
         4.76602148e-03, -1.37065088e-03,  2.00023063e-01,
         5.86447579e-03,  4.43075280e-01],
       [-1.10978155e-01, -1.69022905e-01, -1.87587082e-02,
        -1.60838190e-01, -9.49413269e-02, -7.43257693e-02,
        -5.60070699e-01, -2.33396945e-01, -2.20028398e-01,
        -1.60015969e-02, -2.07541961e-01, -1.01709888e-01,
         1.33060426e-02,  1.05835863e-01,  1.91251019e-03,
         8.56180425e-04, -1.49651751e-01,  1.09086693e-03,
        -1.92253093e-03, -1.72692995e-03, -3.22691532e-02,
        -4.49924965e-03, -2.38762023e-01]])

In [21]:
# Assign the coordinates of each cluster's center to individual variables
cluster1_mean = kmeans.cluster_centers_[0]
cluster2_mean = kmeans.cluster_centers_[1]
cluster3_mean = kmeans.cluster_centers_[2]

In [22]:
# Display the mean (centroid) of cluster 1
cluster1_mean

array([ 4.25034139e-01,  1.67762410e+00, -2.14471158e-03,  1.12999836e+00,
        6.43012965e-01,  3.82899463e-01,  4.15648552e-01, -1.72695722e-02,
        2.26622717e+00,  1.39976427e-01,  2.04856340e+00,  8.56557084e-01,
       -5.78285388e-01, -3.12773529e-01, -4.79531504e-05,  6.72592843e-04,
        1.42787514e+00, -1.62251995e-02,  3.80966102e-03,  1.72146635e-02,
       -2.28969508e-01,  2.18237323e-02,  8.36318546e-01])

In [23]:
# Display the mean (centroid) of cluster 2
cluster2_mean

array([ 1.91066519e-01, -1.31178288e-01,  6.26142344e-02,  6.62852419e-02,
        4.89680949e-02,  8.77080094e-02,  1.67288775e+00,  7.75191978e-01,
       -2.04508726e-01, -4.69622126e-03, -1.56410214e-01, -1.62599929e-02,
        1.93172457e-01, -2.20143935e-01, -6.27447142e-03, -3.09331939e-03,
       -9.25900649e-02,  3.05849997e-03,  4.76602148e-03, -1.37065088e-03,
        2.00023063e-01,  5.86447579e-03,  4.43075280e-01])

In [24]:
# Display the mean (centroid) of cluster 3
cluster3_mean

array([-0.11097816, -0.16902291, -0.01875871, -0.16083819, -0.09494133,
       -0.07432577, -0.5600707 , -0.23339694, -0.2200284 , -0.0160016 ,
       -0.20754196, -0.10170989,  0.01330604,  0.10583586,  0.00191251,
        0.00085618, -0.14965175,  0.00109087, -0.00192253, -0.00172693,
       -0.03226915, -0.00449925, -0.23876202])

## kmedoids Clustering

In [ ]:
# Note: The df_sample line is commented out, meaning the full Clus_dataSet is used.
# Initialize KMedoids model with 3 clusters and a random state for reproducibility
kmedoids = KMedoids(n_clusters=3,random_state=42)
# Fit the KMedoids model to the scaled dataset
kmedoids=kmedoids.fit(Clus_dataSet)

In [ ]:
# Display the first 100 cluster labels assigned by KMedoids
kmedoids.labels_[0:100]

In [ ]:
# Insert the KMedoids cluster labels as a new column at the beginning of the original DataFrame
df.insert(0, 'kmedoids Cluster Labels', kmedoids.labels_)
# Display the first 5 rows of the modified DataFrame to see the new cluster labels
df.head(5)

In [ ]:
# Calculate and print the Silhouette Score for the KMedoids clustering
print('Silhouette Score:', '%.2f'%silhouette_score(Clus_dataSet, kmedoids.labels_))

In [ ]:
# Add the KMedoids cluster labels to the DataFrame containing scaled features
scaled_features_clus['cluster'] = kmedoids.labels_

In [ ]:
# Create separate DataFrames for each cluster based on KMedoids labels
cluster1=scaled_features_clus.query("cluster == 0")
cluster2=scaled_features_clus.query("cluster == 1")
cluster3=scaled_features_clus.query("cluster == 2")

In [ ]:
# Display the first few rows of KMedoids cluster 1
cluster1.head()

In [ ]:
# Display the first few rows of KMedoids cluster 2
cluster2.head()

In [ ]:
# Display the first few rows of KMedoids cluster 3
cluster3.head()

## Hierarchical Clustering

In [2]:
# Initialize AgglomerativeClustering model with 3 clusters, 'euclidean' metric, and 'complete' linkage
# Linkage options include 'ward', 'complete', 'average', 'single'
hcluster = AgglomerativeClustering(n_clusters=3, metric='euclidean',linkage='complete')
# Fit the Hierarchical clustering model to the scaled dataset and predict cluster labels
hcluster.fit_predict(Clus_dataSet)

NameError: name 'AgglomerativeClustering' is not defined

In [1]:
# Display the first 100 cluster labels assigned by Hierarchical Clustering
hcluster.labels_[0:100]

NameError: name 'hcluster' is not defined

In [ ]:
# Count the number of data points assigned to each cluster by Hierarchical Clustering
pd.Series(hcluster.labels_).value_counts()

In [ ]:
# Insert the Hierarchical clustering labels as a new column at the beginning of the original DataFrame
df.insert(0, 'hcluster Cluster Labels', hcluster.labels_)
# Display the first few rows of the modified DataFrame to see the new cluster labels
df.head()

In [ ]:
# Calculate and print the Silhouette Score for the Hierarchical clustering
print('Silhouette Score:', '%.2f'%silhouette_score(Clus_dataSet, hcluster.labels_))

In [ ]:
# Add the Hierarchical clustering labels to the DataFrame containing scaled features
scaled_features_clus['cluster'] = hcluster.labels_

In [ ]:
# Create separate DataFrames for each cluster based on Hierarchical clustering labels
cluster1=scaled_features_clus.query("cluster == 0")
cluster2=scaled_features_clus.query("cluster == 1")
cluster3=scaled_features_clus.query("cluster == 2")

In [ ]:
# Display the first few rows of Hierarchical cluster 1
cluster1.head()

In [ ]:
# Display the first few rows of Hierarchical cluster 2
cluster2.head()

In [ ]:
# Display the first few rows of Hierarchical cluster 3
cluster3.head()